package logic.domainClasses;

public enum Genre {
	ALTERNATIVE, BLUES, CLASSICAL, CLASSICROCK, COUNTRY, ELECTRONICA, FOLK, HEAVYMETAL, HIPHOP, 
	INDIEROCK, JAZZ, RAP, RNB, ROCK, ROCKANDROLL, POP, PUNK, SOUL, SOUNDTRACKS, OTHER;
}
